apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-1
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: wordpress-1
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-2
spec:
  capacity:
    storage: 2oGi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: wordpress-2
    fsType: ext4
