# Dynamic provisioning is implemented using a StorageClass.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---
# PVC uses storageClassName to select a StorageClass
# for fulfilling dynamic provisioning
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  # match a StorageClass named 'fast'
  storageClassName: fast
  resources:
    requests:
      storage: 30Gi
