apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
  labels:
    app: mongodb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: mongodb
data:
  mongodb_url: mongodb-service

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==
  mongo-root-password: bW9uZ29zZWNyZXQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  namespace: mongodb
  labels:
    app: mongodb-deploy
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        resources: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017 
