apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deploy
  namespace: mongodb
  labels:
    app: mongo-express-deploy
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        resources: {}
        env:
        # point to the mongodb service as its server url
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: mongodb_url
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        ports:
        - containerPort: 8081
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongodb
spec:
  selector:
    app: mongo-express
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081

---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
  namespace: mongodb
spec:
  ingressClassName: nginx
  rules:
  - host: mongo-express.atoz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # https://hub.docker.com/_/mongo-express for login account
            name: mongo-express-service
            port:
              number: 8081
